ignore:
    "RotateTest.cs "
    
- name: Codecov
  uses: codecov/codecov-action@v3.1.1
  codecov:
  token: a97d03cf-72ca-4373-a9f9-f29b3ba19e25
  
 
coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    # notification blocks. See: https://docs.codecov.io/docs/codecovyml-reference#section-coverage-notify
  status:
    project:
    patch:
    changes:
